### PR TITLE
minor bug fix (.iloc[i] instead of .loc[i]) and optimization on portfolio

### LINKED ISSUE #31: DataFrame: use .iloc instead of .loc
In some places, df.loc[i] is used, when it should be df.iloc[i].

### PR DESCRIPTION
**Pull request by fmilthaler**
Using .iloc[i] instead of .loc[i], and calling pf._update only once, after portfolio was generated. This closes #31

### CODE REVIEW

**Review by felipsoarez — COMMENTED** [review]
ACK, not tested

**Review by PietropaoloFrisoni — APPROVED** [review]

**Comment by PietropaoloFrisoni** [comment]
It seems indeed much more efficient to update all quantities only at the end of building the portfolio (I also wanted to do something similar in the first place). I assumed updating every time was a deliberate design choice so that users could add/remove stocks and funds dynamically by automatically updating the portfolio. Tests seem to work, so I approved the changes. I hope no strange and unexpected behaviors will appear.

**Comment by fmilthaler** [comment]
Thanks @PietropaoloFrisoni for the review. I ran through all examples and all looks good there as well. 
I think that I originally designed it in a way for the user to manually add a stock to the portfolio post its creation. But that feature is not in master, nor do I think there is much need for it. Hence, the update after all stocks were added makes sense.

**Comment by fmilthaler** [comment]
A similar solution regarding the `_update` calls is in the closed PR #58. Contacted the author to try and recreated their PR as their solution also adds an argument `defer_update`.

**Pull request merged**
