### PR TITLE
Momentum Indicators - RSI, MACD ...

### PR DESCRIPTION
**Pull request by pythonhacker**
Implementation of RSI momentum indicator, ref -> https://github.com/fmilthaler/FinQuant/issues/119

### CODE REVIEW

**Comment by fmilthaler** [comment]
Hey @pythonhacker , love your enthusiasm and you adding new features. Thank you very much.
Expect a review this weekend, as there is quite a bit to go through and do my research on those features myself :)
Anyway, could you please add some unit tests (I know that some of the current features are not well tested, but that will be addressed in the near future). Also, could I ask you to add this to the file `example/Example-Analysis.py` with some nice text etc to showcase these new features to FinQuant's users.

**Comment by fmilthaler** [comment]
FYI: You can ignore the failed pipeline "Formatting and Version Increment...". It's a new pipeline and just ran for the first time on a fork. Added a new issue #124 . Since it failed, the easiest way forward is probably to change the target branch to `fmilthaler:feature/rsi-indicator`. When everything looks good, we'll merge it into that branch, and then the pipeline will run just fine, updating the version and formatting automatically. Following that, we'll merge it into master.

**Comment by pythonhacker** [comment]
> FYI: You can ignore the failed pipeline "Formatting and Version Increment...". It's a new pipeline and just ran for the first time on a fork. Added a new issue #124 . Since it failed, the easiest way forward is probably to change the target branch to `fmilthaler:feature/rsi-indicator`. When everything looks good, we'll merge it into that branch, and then the pipeline will run just fine, updating the version and formatting automatically. Following that, we'll merge it into master.

Got it. Will look into unit-tests and documentation.

**Comment by fmilthaler** [comment]
I'll merge this not into master, but into `feature/rsi-indicator` so that I can make the necessary additions and play around with it before it gets merged into master. Thank you for this addition @pythonhacker. :)

**Pull request merged**
