### PR TITLE
Compute Sortino ratio (#67)

### PR DESCRIPTION
**Pull request by fmilthaler**
Addition of Sortino ratio to FinQuant

### CODE REVIEW

**Comment by PietropaoloFrisoni** [comment]
Amazing, I didn't realize that so much work was already done to add the Sortino Ratio to FinQuant. Thank you so much for your work @aft90 and @fmilthaler! I will happily go into the details and complete the feature implementation as soon as possible. 

Sorry to bother you @fmilthaler, but it looks like some checks (build 3.11) were not successful. I tried to resolve some conflicts which appeared after pulling and pushing an empty commit as a test, and I hope I haven't done any damage : ). Do you have any idea how to solve these?

All the best

**Comment by PietropaoloFrisoni** [comment]
@fmilthaler Ok, it is all fixed now. There was a typo in `version.py` (my bad, I left an empty line while resolving conflicts with the master branch) and apparently a syntax error in the `downside_risk` function, probably due to Python updates since the time in which this PR was initially opened. Tomorrow I'll fix it. Best again!

**Comment by fmilthaler** [comment]
> Amazing, I didn't realize that so much work was already done to add the Sortino Ratio to FinQuant. Thank you so much for your work @aft90 and @fmilthaler! I will happily go into the details and complete the feature implementation as soon as possible.
> 
> Sorry to bother you @fmilthaler, but it looks like some checks (build 3.11) were not successful. I tried to resolve some conflicts which appeared after pulling and pushing an empty commit as a test, and I hope I haven't done any damage : ). Do you have any idea how to solve these?
> 
> All the best

Sorry, I couldn't check it out yesterday, but seems like you got it solved now. Well done :)

**Comment by fmilthaler** [comment]
@PietropaoloFrisoni Apologies for not telling you about this. 
I saw that you updated `README.tex.md` manually, and then your changes were overwritten by the automated script. You should not update the `README.tex.md`. The actual readme of the project is `README.md`. When you make changes in there, they are automatically ported over to `README.tex.md` (just to keep that file up to date). By now it is somewhat of an redundant version, which was initially used to get the LaTeX equations into README.md. 

Anyways, make your changes in `README.md`, not `README.tex.md` :)

**Comment by PietropaoloFrisoni** [comment]
Thank you, Frank. I was actually going to ask you what was going on XD.

Before next week I'll most probably complete this PR (I would like to perform some sanity checks on the Sortino Ratio with other sources first).

All the best

**Comment by PietropaoloFrisoni** [comment]
Ultimately, I implemented the Sortino ratio described in [this document](https://www.cmegroup.com/education/files/rr-sortino-a-sharper-ratio.pdf). 

Different documents and tutorials seem to implement a slightly different version of the Sortino ratio. Performing the same test with the portfolio described in [this example](https://quant.stackexchange.com/questions/68556/how-to-calculate-sortino-ratio-from-a-weighted-portfolio-with-python) using `FinQuant` provides the same result of `PerformanceAnalytics` R package, which provides a function to compute the Sortino ratio. (There is a slight difference since the example considers _Close Price_ instead of the _Adjusted Close Price_, but using the same format gives precisely the same output).

@fmilthaler Please let me know if you like the current order in which the portfolio parameters are displayed or if there is anything you want to add/remove/change : )

All the best

**Comment by fmilthaler** [comment]
Excellent, I'll take a more detailled look at it tomorrow. 
Could you please add this to one of the examples? I guess Example-Analysis would be the best place?!

**Comment by PietropaoloFrisoni** [comment]
> Excellent, I'll take a more detailled look at it tomorrow. Could you please add this to one of the examples? I guess Example-Analysis would be the best place?

Yep, I keep forgetting about updating the examples. I'll add it tomorrow 👍

**Comment by fmilthaler** [comment]
Other than the docstring comment (which you actually did correctly, strictly speaking), this looks good to me. Will approve and merge as soon as the comment is re-added.

**Comment by fmilthaler** [comment]
One additional request: Could you add this line to `CONTRIBUTORS.md`:
```
- @aft90: helped to implement the Sortino Ratio
```

**Review by fmilthaler — COMMENTED** [review]
As mentioned in the comments with more details:
1. please revert the change of removing part of the docstring, and
2. update the list of contributors

**Review by fmilthaler — COMMENTED** [review]
Since I was part of this PR, I cannot formally approve, but unofficial I do. Ready to be merged.

**Review by PietropaoloFrisoni — APPROVED** [review]

**Pull request merged**
