### PR TITLE
Added defer_update flag to add_stock function

### LINKED ISSUE #57: pf._udpate() called numerous times when adding stocks in bulk.
I noticed when adding a number of stocks to a portfolio the time to add them takes longer and longer. Adding a deferment to the pf._update() call seems to resolve this and makes adding bulk stocks much faster. Pull request to follow for your consideration.

### PR DESCRIPTION
**Pull request by fmilthaler**
Added defer_update flag to add_stock function so bulk adding of stocks can have update deferred until after all are added.

This closes #57.

### CODE REVIEW

**Comment by fmilthaler** [comment]
Converting this to draft to block it from being merged until #108 is merged.

**Comment by fmilthaler** [comment]
@nuvious Have you decided how you want to be listed in `CONTRIBUTORS.md`? Just your GitHub username or username + full name?

**Comment by nuvious** [comment]
> @nuvious Have you decided how you want to be listed in `CONTRIBUTORS.md`? Just your GitHub username or username + full name?

Username + full name is desired.

**Comment by fmilthaler** [comment]
@nuvious cute cat btw ;)

**Review by PietropaoloFrisoni — APPROVED** [review]
@nuvious thanks, cute cat indeed!

**Pull request merged**
